export const GET_INTERFACE_DATA = "GET_INTERFACE_DATA";
export const GET_INTERFACE_DATA_SUCCESS = "GET_INTERFACE_DATA_SUCCESS";
export const GET_INTERFACE_DATA_FAIL = "GET_INTERFACE_DATA_FAIL";

//Update InterfaceData
export const UPDATE_INTERFACE_CONFIG_DATA = "UPDATE_INTERFACE_DATA";
export const UPDATE_INTERFACE_CONFIG_DATA_SUCCESS = "UPDATE_INTERFACE_DATA_SUCCESS";
export const UPDATE_INTERFACE_CONFIG_DATA_FAIL = "UPDATE_INTERFACE_DATA_FAIL";

//get InterfaceCofigData
export const GET_INTERFACE_CONFIG_DATA = "GET_INTERFACE_CONFIG_DATA";
export const GET_INTERFACE_CONFIG_DATA_SUCCESS = "GET_INTERFACE_CONFIG_DATA_SUCCESS";
export const GET_INTERFACE_CONFIG_DATA_FAIL = "GET_INTERFACE_CONFIG_DATA_FAIL";

//OCNOS DEVICE ISIS Action
export const OCNOS_ISIS_GET_ACTION_TYPE = "OCNOS_ISIS_GET_ACTION_TYPE";
export const OCNOS_ISIS_GET_SUCCESS_ACTION_TYPE = "OCNOS_ISIS_GET_SUCCESS_ACTION_TYPE";
export const OCNOS_ISIS_GET_FAIL_ACTION_TYPE = "OCNOS_ISIS_GET_FAIL_ACTION_TYPE";
