// Topology Logs Configuration

// GET
export const GET_ALARMS_DATA_SUCCESS = "GET_ALARMS_DATA_SUCCESS";
export const GET_ALARMS_DATA_FAIL = "GET_ALARMS_DATA_FAIL";
export const GET_ALARMS_DATA = "GET_ALARMS_DATA";


//SYSLOG GET
export const GET_SYSLOG_DATA_SUCCESS = "GET_SYSLOG_DATA_SUCCESS";
export const GET_SYSLOG_DATA_FAIL = "GET_SYSLOG_DATA_FAIL";
export const GET_SYSLOG_DATA = "GET_SYSLOG_DATA";

//DEVICE LOGS

export const POST_LOGS_DEVICE_DATA = "POST_LOGS_DEVICE_DATA";
export const POST_LOGS_DEVICE_DATA_FAIL = "POST_LOGS_DEVICE_DATA_FAIL";
export const POST_LOGS_DEVICE_DATA_SUCCESS = "POST_LOGS_DEVICE_DATA_SUCCESS";

//DEVICE ALARMS
export const POST_ALARM_EVENTS_DATA = "POST_ALARM_EVENTS_DATA";
export const POST_ALARM_EVENTS_DATA_FAIL = "POST_ALARM_EVENTS_DATA_FAIL";
export const POST_ALARM_EVENTS_DATA_SUCCESS = "POST_ALARM_EVENTS_DATA_SUCCESS";

export const POST_ALARM_EVENTS_DEVICE_DATA = "POST_ALARM_EVENTS_DEVICE_DATA";
export const POST_ALARM_EVENTS_DEVICE_DATA_FAIL = "POST_ALARM_EVENTS_DEVICE_DATA_FAIL";
export const POST_ALARM_EVENTS_DEVICE_DATA_SUCCESS = "POST_ALARM_EVENTS_DEVICE_DATA_SUCCESS";

export const POST_ALARM_EVENTS_LATEST5_DATA = "POST_ALARM_EVENTS_LATEST5_DATA";
export const POST_ALARM_EVENTS_LATEST5_DATA_FAIL = "POST_ALARM_EVENTS_LATEST5_DATA_FAIL";
export const POST_ALARM_EVENTS_LATEST5_DATA_SUCCESS = "POST_ALARM_EVENTS_LATEST5_DATA_SUCCESS";

export const POST_LOGS_DATA_ACTION_TYPE = "POST_LOGS_DATA_ACTION_TYPE";
export const POST_LOGS_DATA_ACTION_TYPE_FAIL = "POST_LOGS_DATA_ACTION_TYPE_FAIL";
export const POST_LOGS_DATA_ACTION_TYPE_SUCCESS = "POST_LOGS_DATA_ACTION_TYPE_SUCCESS";

export const DELETE_ALL_DEVICES_ALARMS_EVENTS = "DELETE_ALL_DEVICES_ALARMS_EVENTS";
export const DELETE_ALL_DEVICES_ALARMS_EVENTS_SUCCESS = "DELETE_ALL_DEVICES_ALARMS_EVENTS_SUCCESS";
export const DELETE_ALL_DEVICES_ALARMS_EVENTS_FAIL = "DELETE_ALL_DEVICES_ALARMS_EVENTS_FAIL";

export const DELETE_PARTICULAR_DEVICES_ALARMS_EVENTS = "DELETE_PARTICULAR_DEVICES_ALARMS_EVENTS";
export const DELETE_PARTICULAR_DEVICES_ALARMS_EVENTS_SUCCESS = "DELETE_PARTICULAR_DEVICES_ALARMS_EVENTS_SUCCESS";
export const DELETE_PARTICULAR_DEVICES_ALARMS_EVENTS_FAIL = "DELETE_PARTICULAR_DEVICES_ALARMS_EVENTS_FAIL";

export const DELETE_PARTICULAR_DEVICES_ALL_ALARMS_EVENTS = "DELETE_PARTICULAR_DEVICES_ALL_ALARMS_EVENTS";
export const DELETE_PARTICULAR_DEVICES_ALL_ALARMS_EVENTS_SUCCESS = "DELETE_PARTICULAR_DEVICES_ALL_ALARMS_EVENTS_SUCCESS";
export const DELETE_PARTICULAR_DEVICES_ALL_ALARMS_EVENTS_FAIL = "DELETE_PARTICULAR_DEVICES_ALL_ALARMS_EVENTS_FAIL";

export const GET_ALARMS_EVENT_DATA_ACTION = "GET_ALARMS_EVENT_DATA_ACTION";
export const GET_ALARMS_EVENT_DATA_ACTION_SUCCESS = "GET_ALARMS_EVENT_DATA_ACTION_SUCCESS";
export const GET_ALARMS_EVENT_DATA_ACTION_FAIL = "GET_ALARMS_EVENT_DATA_ACTION_FAIL";
