// Devices List

// GET
export const GET_DEVICES_DATA_SUCCESS = "GET_DEVICES_DATA_SUCCESS";
export const GET_DEVICES_DATA_FAIL = "GET_DEVICES_DATA_FAIL";
export const GET_DEVICES_DATA = "GET_DEVICES_DATA";

// DELETE
// GET
export const DELETE_DEVICES_DATA_SUCCESS = "DELETE_DEVICES_DATA_SUCCESS";
export const DELETE_DEVICES_DATA_FAIL = "DELETE_DEVICES_DATA_FAIL";
export const DELETE_DEVICES_DATA = "DELETE_DEVICES_DATA";

// UPDATE
export const UPDATE_DEVICE_SETTING = "UPDATE_DEVICE_SETTING";
export const UPDATE_DEVICE_SETTING_SUCCESS = "UPDATE_DEVICE_SETTING_SUCCESS";
export const UPDATE_DEVICE_SETTING_FAIL = "UPDATE_DEVICE_SETTING_FAIL";

// GET DEVICE PROCESS INFO
export const GET_DEVICE_PROCESS_INFO_SUCCESS =
  "GET_DEVICE_PROCESS_INFO_SUCCESS";
export const GET_DEVICE_PROCESS_INFO_FAIL = "GET_DEVICE_PROCESS_INFO_FAIL";
export const GET_DEVICE_PROCESS_INFO = "GET_DEVICE_PROCESS_INFO";

// GET DEVICE SYSTEM INFO
export const GET_DEVICE_SYSTEM_INFO_SUCCESS = "GET_DEVICE_SYSTEM_INFO_SUCCESS";
export const GET_DEVICE_SYSTEM_INFO_FAIL = "GET_DEVICE_SYSTEM_INFO_FAIL";
export const GET_DEVICE_SYSTEM_INFO = "GET_DEVICE_SYSTEM_INFO";
// GET DEVICE STATS INFO
export const GET_DEVICE_STATS_INFO_SUCCESS = "GET_DEVICE_STATS_INFO_SUCCESS";
export const GET_DEVICE_STATS_INFO_FAIL = "GET_DEVICE_STATS_INFO_FAIL";
export const GET_DEVICE_STATS_INFO = "GET_DEVICE_STATS_INFO";
// DELETE DEVICE STATS INFO
export const DELETE_DEVICE_STATS_INFO_SUCCESS = "DELETE_DEVICE_STATS_INFO_SUCCESS";
export const DELETE_DEVICE_STATS_INFO_FAIL = "DELETE_DEVICE_STATS_INFO_FAIL";
export const DELETE_DEVICE_STATS_INFO = "DELETE_DEVICE_STATS_INFO";


// GET DEVICE Custum Graph INFO
export const GET_DEVICE_CUSTUM_GRAPH_LIST_SUCCESS = "GET_DEVICE_CUSTOM_GRAPH_LIST_SUCCESS";
export const GET_DEVICE_CUSTUM_GRAPH_LIST_FAIL = "GET_DEVICE_CUSTOM_GRAPH_LIST_FAIL";
export const GET_DEVICE_CUSTUM_GRAPH_LIST = "GET_DEVICE_CUSTOM_GRAPH_LIST_INFO";



//SET DEVICE HISTORICAL INFO
export const SET_DEVICE_HISTORICAL_INFO_SUCCESS = "SET_DEVICE_HISTORICAL_INFO_SUCCESS";
export const SET_DEVICE_HISTORICAL_INFO_FAIL = "SET_DEVICE_HISTORICAL_INFO_FAIL";
export const SET_DEVICE_HISTORICAL_INFO = "SET_DEVICE_HISTORICAL_INFO";


//SET CUSTUM FIELD BY OID 
export const CREATE_CUSTUM_FIELD_BY_OID_SUCCESS = "CREATE_CUSTUM_FIELD_BY_OID_SUCCESS";
export const CREATE_CUSTUM_FIELD_BY_OID_FAIL = "CREATE_CUSTUM_FIELD_BY_OID_FAIL";
export const CREATE_CUSTUM_FIELD_BY_OID_INFO = "CREATE_CUSTUM_FIELD_BY_OID_INFO";


// GET OID List
export const GET_OID_LIST_SUCCESS = "GET_OID_LIST_SUCCESS";
export const GET_OID_LIST_FAIL = "GET_OID_LIST_FAIL";
export const GET_OID_LIST = "GET_OID_LIST";



// Delete Oid From List
export const DELETE_OID_LIST_SUCCESS = "DELETE_OID_LIST_SUCCESS";
export const DELETE_OID_LIST_FAIL = "DELETE_OID_LIST_FAIL";
export const DELETE_OID_LIST = "DELETE_OID_LIST";
//SET POLLING INTERVAL
export const SET_DEVICE_POLLING_INTERVAL_SUCCESS = "SET_DEVICE_POLLING_INTERVAL_SUCCESS";
export const SET_DEVICE_POLLING_INTERVAL_FAIL = "SET_DEVICE_POLLING_INTERVAL_FAIL";
export const SET_DEVICE_POLLING_INTERVAL = "SET_DEVICE_POLLING_INTERVAL";

//SET PROCESS INTERVAL
export const SET_DEVICE_PROCESS_INTERVAL_SUCCESS = "SET_DEVICE_PROCESS_INTERVAL_SUCCESS";
export const SET_DEVICE_PROCESS_INTERVAL_FAIL = "SET_DEVICE_PROCESS_INTERVAL_FAIL";
export const SET_DEVICE_PROCESS_INTERVAL = "SET_DEVICE_PROCESS_INTERVAL";

// SET DEVICE POLLING
export const SET_DEVICE_POLLING = "SET_DEVICE_POLLING";
export const SET_DEVICE_POLLING_SUCCESS = "SET_DEVICE_POLLING_SUCCESS";
export const SET_DEVICE_POLLING_FAIL = "SET_DEVICE_POLLING_FAIL";

// GET DEVICE POLLING
export const GET_DEVICE_POLLING = "GET_DEVICE_POLLING";
export const GET_DEVICE_POLLING_SUCCESS = "GET_DEVICE_POLLING_SUCCESS";
export const GET_DEVICE_POLLING_FAIL = "GET_DEVICE_POLLING_FAIL";

// GET DEVICE CREDENTIALS
export const GET_DEVICE_CREDENTIALS = "GET_DEVICE_CREDENTIALS";
export const GET_DEVICE_CREDENTIALS_SUCCESS = "GET_DEVICE_CREDENTIALS_SUCCESS";
export const GET_DEVICE_CREDENTIALS_FAIL = "GET_DEVICE_CREDENTIALS_FAIL";


// Verify license 
export const VERIFY_LICENSE = "VERIFY_LICENSE_KEY";
export const VERIFY_LICENSE_SUCCESS = "VERIFY_LICENSE_KEY_SUCCESS";
export const VERIFY_LICENSE_FAIL = "VERIFY_LICENSE_KEY_FAIL";

// Reboot Device 
export const REBOOT_DEVICE = "REBOOT_DEVICE";
export const REBOOT_DEVICE_SUCCESS = "REBOOT_DEVICE_SUCCESS";
export const REBOOT_DEVICE_FAIL = "REBOOT_DEVICE_FAIL";

//Register Device
export const REGISTER_DEVICE_ACTION_TYPE = "REGISTER_DEVICE_ACTION_TYPE";
export const REGISTER_DEVICE_SUCCESS_ACTION_TYPE = "REGISTER_DEVICE_SUCCESS_ACTION_TYPE";
export const REGISTER_DEVICE_FAIL_ACTION_TYPE = "REGISTER_DEVICE_FAIL_ACTION_TYPE";

//Syslog Device IP
export const SYSLOG_DEVICE_ACTION_TYPE = "SYSLOG_DEVICE_ACTION_TYPE";
export const SYSLOG_DEVICE_SUCCESS_ACTION_TYPE = "SYSLOG_DEVICE_SUCCESS_ACTION_TYPE";
export const SYSLOG_DEVICE_FAIL_ACTION_TYPE = "SYSLOG_DEVICE_FAIL_ACTION_TYPE";


