export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";

export const ADD_USER_DATA = "ADD_USER_DATA";
export const ADD_USER_DATA_SUCCESS = "ADD_USER_DATA_SUCCESS";
export const ADD_USER_DATA_FAIL = "ADD_USER_DATA_FAIL";

export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAIL = "UPDATE_USER_DATA_FAIL";

export const DELETE_USER_DATA_BY_ID = "DELETE_USER_DATA";
export const DELETE_USER_DATA_SUCCESS_BY_ID = "DELETE_USER_DATA_SUCCESS";
export const DELETE_USER_DATA_FAIL_BY_ID = "DELETE_USER_DATA_FAIL";

export const GET_USER_DATA_BY_ID = "GET_USER_DATA_BY_ID"
export const GET_USER_DATA_BY_ID_SUCCESS = "GET_USER_DATA_BY_ID_SUCCESS"
export const GET_USER_DATA_BY_ID_FAIL = "GET_USER_DATA_BY_ID_FAIL"

export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL"