// Topology Viewer Configuration

// GET
export const GET_NODES_DATA_SUCCESS = "GET_NODES_DATA_SUCCESS";
export const GET_NODES_DATA_FAIL = "GET_NODES_DATA_FAIL";
export const GET_NODES_DATA = "GET_NODES_DATA";
export const GET_EDGES_DATA_SUCCESS = "GET_EDGES_DATA_SUCCESS";
export const GET_EDGES_DATA_FAIL = "GET_EDGES_DATA_FAIL";
export const GET_EDGES_DATA = "GET_EDGES_DATA";