// Get device configured data
export const GET_MAP_CONFIG_DATA_SUCCESS = "GET_MAP_CONFIG_DATA_SUCCESS";
export const GET_MAP_CONFIG_DATA_FAIL = "GET_MAP_CONFIG_DATA_FAIL";
export const GET_MAP_CONFIG_DATA = "GET_MAP_CONFIG_DATA";

// Set device configuration

export const SET_MAP_CONFIG_DATA_SUCCESS = "SET_MAP_CONFIG_DATA_SUCCESS";
export const SET_MAP_CONFIG_DATA_FAIL = "SET_MAP_CONFIG_DATA_FAIL";
export const SET_MAP_CONFIG_DATA = "SET_MAP_CONFIG_DATA";

// Interfaces Configuration

// GET
export const GET_PACKET_BROKER_INTERFACES_DATA_SUCCESS = "GET_PACKET_BROKER_INTERFACES_DATA_SUCCESS";
export const GET_PACKET_BROKER_INTERFACES_DATA_FAIL = "GET_PACKET_BROKER_INTERFACES_DATA_FAIL";
export const GET_PACKET_BROKER_INTERFACES_DATA = "GET_PACKET_BROKER_INTERFACES_DATA";

// SET
export const SET_PACKET_BROKER_INTERFACES_DATA_SUCCESS = "SET_PACKET_BROKER_INTERFACES_DATA_SUCCESS";
export const SET_PACKET_BROKER_INTERFACES_DATA_FAIL = "SET_PACKET_BROKER_INTERFACES_DATA_FAIL";
export const SET_PACKET_BROKER_INTERFACES_DATA = "SET_PACKET_BROKER_INTERFACES_DATA";

// Map configuration

//GET
export const GET_MAP_DATA_SUCCESS = "GET_MAP_DATA_SUCCESS";
export const GET_MAP_DATA_FAIL = "GET_MAP_DATA_FAIL";
export const GET_MAP_DATA = "GET_MAP_DATA";
//POST
export const SET_MAP_DATA_SUCCESS = "SET_MAP_DATA_SUCCESS";
export const SET_MAP_DATA_FAIL = "SET_MAP_DATA_FAIL";
export const SET_MAP_DATA = "SET_MAP_DATA";
//PUT
export const UPDATE_MAP_DATA_SUCCESS = "UPDATE_MAP_DATA_SUCCESS";
export const UPDATE_MAP_DATA_FAIL = "UPDATE_MAP_DATA_FAIL";
export const UPDATE_MAP_DATA = "UPDATE_MAP_DATA";
//DELETE
export const DELETE_MAP_DATA_SUCCESS = "DELETE_MAP_DATA_SUCCESS";
export const DELETE_MAP_DATA_FAIL = "DELETE_MAP_DATA_FAIL";
export const DELETE_MAP_DATA = "DELETE_MAP_DATA";

// Rules configuration
//GET
export const GET_RULE_DATA_SUCCESS = "GET_RULE_DATA_SUCCESS";
export const GET_RULE_DATA_FAIL = "GET_RULE_DATA_FAIL";
export const GET_RULE_DATA = "GET_RULE_DATA";

export const GET_ONE_RULE_DATA_SUCCESS = "GET_ONE_RULE_DATA_SUCCESS";
export const GET_ONE_RULE_DATA_FAIL = "GET_ONE_RULE_DATA_FAIL";
export const GET_ONE_RULE_DATA = "GET_ONE_RULE_DATA";

//POST
export const SET_RULE_DATA_SUCCESS = "SET_RULE_DATA_SUCCESS";
export const SET_RULE_DATA_FAIL = "SET_RULE_DATA_FAIL";
export const SET_RULE_DATA = "SET_RULE_DATA";
//PUT
export const UPDATE_RULE_DATA_SUCCESS = "UPDATE_RULE_DATA_SUCCESS";
export const UPDATE_RULE_DATA_FAIL = "UPDATE_RULE_DATA_FAIL";
export const UPDATE_RULE_DATA = "UPDATE_RULE_DATA";
//DELETE
export const DELETE_RULE_DATA_SUCCESS = "DELETE_RULE_DATA_SUCCESS";
export const DELETE_RULE_DATA_FAIL = "DELETE_RULE_DATA_FAIL";
export const DELETE_RULE_DATA = "DELETE_RULE_DATA";

// Portchannel configuration
//GET
export const GET_PORTCHANNEL_DATA_SUCCESS = "GET_PORTCHANNEL_DATA_SUCCESS";
export const GET_PORTCHANNEL_DATA_FAIL = "GET_PORTCHANNEL_DATA_FAIL";
export const GET_PORTCHANNEL_DATA = "GET_PORTCHANNEL_DATA";

//POST
export const SET_PORTCHANNEL_DATA_SUCCESS = "SET_PORTCHANNEL_DATA_SUCCESS";
export const SET_PORTCHANNEL_DATA_FAIL = "SET_PORTCHANNEL_DATA_FAIL";
export const SET_PORTCHANNEL_DATA = "SET_PORTCHANNEL_DATA";

//PUT
export const UPDATE_PORTCHANNEL_DATA_SUCCESS = "UPDATE_PORTCHANNEL_DATA_SUCCESS";
export const UPDATE_PORTCHANNEL_DATA_FAIL = "UPDATE_PORTCHANNEL_DATA_FAIL";
export const UPDATE_PORTCHANNEL_DATA = "UPDATE_PORTCHANNEL_DATA";

//DELETE
export const DELETE_PORTCHANNEL_DATA_SUCCESS = "DELETE_PORTCHANNEL_DATA_SUCCESS";
export const DELETE_PORTCHANNEL_DATA_FAIL = "DELETE_PORTCHANNEL_DATA_FAIL";
export const DELETE_PORTCHANNEL = "DELETE_PORTCHANNEL";
export const DELETE_PORTCHANNEL_ALL_MEMBERS = "DELETE_PORTCHANNEL_ALL_MEMBERS";
export const DELETE_PORTCHANNEL_ALL_MEMBERS_SUCCESS = "DELETE_PORTCHANNEL_ALL_MEMBERS_SUCCESS";
export const DELETE_PORTCHANNEL_ALL_MEMBERS_FAIL = "DELETE_PORTCHANNEL_ALL_MEMBERS_FAIL";
export const DELETE_PORTCHANNEL_PARTICULAR_MEMBERS = "DELETED_PORTCHANNEL_PARTICULAR_MEMBERS";
export const DELETE_PORTCHANNEL_PARTICULAR_MEMBERS_SUCCESS = "DELETE_PORTCHANNEL_PARTICULAR_MEMBERS_SUCCESS";
export const DELETE_PORTCHANNEL_PARTICULAR_MEMBERS_FAIL = "DELETE_PORTCHANNEL_PARTICULAR_MEMBERS_FAIL";

// Getting interface counters
//GET
export const GET_INTERFACE_COUNT_SUCCESS = "GET_INTERFACE_COUNT_SUCCESS";
export const GET_INTERFACE_COUNT_FAIL = "GET_INTERFACE_COUNT_FAIL";
export const GET_INTERFACE_COUNT = "GET_INTERFACE_COUNT";
// Getting DPBSTAT
//GET
export const GET_DPBSTAT_SUCCESS = "GET_DPBSTAT_SUCCESS";
export const GET_DPBSTAT_FAIL = "GET_DPBSTAT_FAIL";
export const GET_DPBSTAT = "GET_DPBSTAT";
