export const GET_OPTICAL_MONITOR_DATA = "GET_OPTICAL_MONITOR_DATA";
export const GET_OPTICAL_MONITOR_DATA_SUCCESS = "GET_OPTICAL_MONITOR_DATA_SUCCESS";
export const GET_OPTICAL_MONITOR_DATA_FAIL = "GET_OPTICAL_MONITOR_DATA_FAIL";
